### ISSUE TITLE
Unable to install coq-vpl

### ISSUE THREAD

**Issue by bollu** [VERIMAG-Polyhedra/opam-vpl#1]
Hello,

I'm a noob to Coq / opam in general, so some help would be lovely.

I've been trying to install `vpl-coq`. It dies with:

```
╭─bollu@cantordust ~/work/proofs  
╰─$ opam install coq-vpl
The following actions will be performed:
  - install coq-vpl 0.2.1

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ERROR] The sources of the following couldn't be obtained, aborting:
          - coq-vpl.0.2.1
        (This may be fixed by running 'opam update')
```

On the other hand, `opam update` runs fine, with the output:

```
╭─bollu@cantordust ~/work/proofs  
╰─$ opam update                                                                                                              66 ↵

=-=- Updating package repositories =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[vpl] synchronized from http://www-verimag.imag.fr/~boulme/opam-vpl
[coq-released] synchronized from https://coq.inria.fr/opam/released
[default] synchronized from https://opam.ocaml.org

=-=- Synchronizing development packages -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[vpl-core] https://github.com/VERIMAG-Polyhedra/vpl already up-to-date

```

I'd appreciate any help in getting this up-and-running.

**Comment by boulme** [comment]
Hello Siddharth,

Thanks a lot for reporting us this issue.

Could you please run opam with debug options and send us the ouput ? This would help us to understand what happens (the error message is very strange: this seems a download issue, not a compile issue).

For example, you could run the following command, and then attach the generated file `opam-install-coq-vpl.log` to your next comment on this issue.

  opam install coq-vpl --debug >& opam-install-coq-vpl.log

Or, if you prefer, you may also try to extract the relevant parts of this file and copy-paste them in your next comment.

Thanks for your help.

Sylvain.

**Comment by bollu** [comment]
```
╭─bollu@cantordust /tmp/install  
╰─$ export OPAMVERBOSE=1;  opam install coq-vpl -v
The following actions will be performed:
  - install coq-vpl 0.2.1

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ERROR] The sources of the following couldn't be obtained, aborting:
          - coq-vpl.0.2.1
        (This may be fixed by running 'opam update')
'opam install coq-vpl -v' failed.
```

The link to the `debug` file [is here in this link](https://gist.github.com/bollu/ba762c03cea0449ac70c89cacf344f85).
```
Raw:

https://gist.github.com/bollu/ba762c03cea0449ac70c89cacf344f85
```

Thanks for the help!

**Comment by bollu** [comment]
Bump :)

**Comment by bollu** [comment]
Changing two things made it work:
1. I was behind a proxy, so I connected without the proxy
2. I updated opam with `opam update` and `opam ugrade`.

These seemed to have done the trick!
